### ISSUE TITLE
New version of Service_framework not working on runtime_browser

### ISSUE THREAD

**Issue by ishantiw** [reTHINK-project/dev-service-framework#58]
We are getting an error (snapshot below) when we are trying to run [Browser: guid.html](https://github.com/reTHINK-project/dev-runtime-browser/blob/develop-GraphConnector-Test/example/guid.html) . When we run it with older version of service_framework then it's working for us but when we run it with the new version it throws `TypeError: IllegalInvocation` error. 
![image](https://cloud.githubusercontent.com/assets/9600691/17927802/c33f1ae4-69f7-11e6-8ea2-37c30d6540c6.png)

**Comment by vitormsilva** [comment]
You have the last version of toolkit?
You did `npm update` or `npm install`?

This was fixed with issue #52;

**Comment by ishantiw** [comment]
I did `npm update` and then it's not working. So do I need to add following piece of code to the RuntimeFactory of runtime_browser?
```const RuntimeFactory = Object.create({
    //....
    atob(b64) {
      return atob(b64);
    },
    //...
});```

**Comment by vitormsilva** [comment]
You shouldn't do nothing.
If you are using the toolkit on master branch, the runtime-browser should be updated as you can see [here](https://github.com/reTHINK-project/dev-runtime-browser/blob/master/src/RuntimeFactory.js#L49)

Could you delete the `node_modules` folder and do `npm install`

**Comment by ishantiw** [comment]
I don't understand what is tookit? Are you referring to dev-hyperty-toolkit, maybe I'm missing something here. And I've tried to delete `node_modules` and `npm install` but it didn't work.

**Comment by ishantiw** [comment]
Well I added above mentioned code to the RuntimeFactory and did `npm update` and it's working now. But I still don't understand what you wrote about the toolkit.

**Comment by vitormsilva** [comment]
By I understand now, you are using the runtime-browser, to work, right?
The [toolkit](https://github.com/reTHINK-project/dev-hyperty-toolkit) was a help to load and test hyperties;
I think you are using an outdated version of runtime-browser because in the master branch, the examples were removed.

But i think you can close this issue;

**Comment by ishantiw** [comment]
Yes I'm using the outdated branch and I have the `example` folder. But anyways its working now. Thanks!
